FROM golang

MAINTAINER shenqi329 <shenqi329@163.com>

RUN apt-get update
RUN apt-get install libpcrecpp0
RUN apt-get -y install mongodb supervisor

RUN go get github.com/labstack/echo gopkg.in/mgo.v2 github.com/dgrijalva/jwt-go


