FROM shenqi329/base_env

MAINTAINER shenqi329 <shenqi329@163.com>

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /go/src/easynote/

RUN go build main.go

EXPOSE 80

CMD ["/usr/bin/supervisord"]


